# CLASS 2

## Python

Create a list

It is an ordered container of arbitrary length that can hold a heterogenous collection of objects 

In [1]:
a = [2,3,4,5]
b = [1,1,1,1]

In [2]:
c = ['f',1]

In [3]:
d = [a,6]

In [4]:
c

In [5]:
d

In [15]:
f = list(range(11, 27, 3))

In [16]:
f

[11, 14, 17, 20, 23, 26]

Adding two lists...

In [6]:
a+b

Now, multiply two lists...

In [7]:
a*b

TypeError: can't multiply sequence by non-int of type 'list'

Multiply a list by a scalar:

In [8]:
2*a

[2, 3, 4, 5, 2, 3, 4, 5]

In [9]:
3*c

['f', 1, 'f', 1, 'f', 1]

How can we handle data?

Now, how to create a vector?

In [10]:
import numpy as np

In [11]:
X = np.ones((3,2))        # array with 3 rows, 2 columns, filled with ones
W = np.zeros(4)           # vector, filled with zeros
Y = np.array([1,2,3])     # a 1D array initialised using a list [1,2,3]
Z = np.linspace(2,3,100)  # an array with 100 points beteen (and including) 2 and 3

In [12]:
W

array([0., 0., 0., 0.])

In [13]:
np.array?

Some operations with arrays

In [14]:
X

X*1.5

array([[1.5, 1.5],
       [1.5, 1.5],
       [1.5, 1.5]])

In [15]:
print(X)
print(X*1.5)  # all elements of X times 1.5

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1.5 1.5]
 [1.5 1.5]
 [1.5 1.5]]


In [16]:
X+Y

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [17]:
X.T + Y

array([[2., 3., 4.],
       [2., 3., 4.]])

In [18]:
V = np.array([1,1,2])

In [19]:
Y+V

array([2, 3, 5])

In [20]:
V-Y

array([ 0, -1, -1])

Multiply two vectors - element-wise

In [21]:
Y*V

array([1, 2, 6])

Dot product

In [22]:
np.dot(Y,V)

9

In [23]:
np.dot(V,V)

6

Cosine calculation

input: radians

In [45]:
np.cos(0)

1.0

In [46]:
np.cos(np.pi/2)

6.123233995736766e-17

Dot product...

Example when there are three dimensions

Calculate dot product of two vectors using a cosine (u.v = |u|*|v|*cos(?)),
If u = (1,2,2), v = (0,1,2), and cos(?) = .89444

In [48]:
(np.sqrt(1^2+2^2+2^2))*(np.sqrt(0^2+1^2+2^2))*.89444

3.4641512241817622

The function arccos in numpy calculates the angle, given the cosine, in radians

In [50]:
np.arccos(.8944272)

0.4636475888760059

In [51]:
# from radians to grades:
np.arccos(.8944272)*180/np.pi

26.56505002401187